/**
 * Parameter Flow Contract Tests
 *
 * Verifies that every user-facing parameter flows from ParameterGenerator
 * through the config pipeline to the engine that consumes it. Catches:
 *   - Naming mismatches (e.g. meshSize vs meshCount)
 *   - Dead params (generated but never read by any engine)
 *   - Missing params (engine reads a key that no config provides)
 *
 * If you add a new parameter to any engine, add it to the contract here.
 * If you add a new config key to ParameterGenerator, map it to the engine
 * that consumes it. Dead params go in KNOWN_UNIMPLEMENTED.
 */

const ParameterGenerator = require('../../lib/analysis/ParameterGenerator');
const PosterizationEngine = require('../../lib/engines/PosterizationEngine');
const SeparationEngine = require('../../lib/engines/SeparationEngine');
const ProxyEngine = require('../../lib/engines/ProxyEngine');

// ─── Authoritative Contracts ─────────────────────────────────────────
// These are the EXACT option keys each engine reads from its options arg.
// Extracted by grepping every `options.XXX` reference in each method.

/** Keys read by PosterizationEngine.posterize() and its sub-engines */
const POSTERIZATION_ENGINE_READS = new Set([
    // Dispatch-level (posterize method)
    'engine',               // Unified engine field (replaces legacy engineType + engineMode)
    'engineType',           // Legacy alias (backward compat)
    'enableGridOptimization',
    'snapThreshold',
    'enableHueGapAnalysis',
    'centroidStrategy',
    'tuning',               // Full tuning object (overrides individual keys below)
    'forcedCentroids',
    'grayscaleOnly',
    'bitDepth',

    // Tuning.split (built from options if tuning not provided)
    'highlightBoost',
    'vibrancyBoost',
    'chromaAxisWeight',
    'neutralIsolationThreshold',
    'warmABoost',

    // Tuning.prune
    'paletteReduction',     // → tuning.prune.threshold
    'hueLockAngle',
    'highlightThreshold',   // → tuning.prune.whitePoint
    'shadowPoint',
    'isolationThreshold',
    'enablePaletteReduction',

    // Tuning.centroid
    'lWeight',
    'cWeight',
    'bWeight',
    'blackBias',
    'vibrancyMode',
    // vibrancyBoost also used in centroid (duplicate, already listed)

    // Sub-engine specific (Mk1.0 / Mk1.5)
    'preserveWhite',
    'preserveBlack',
    'substrateMode',
    'substrateTolerance',
    'refinementPasses',
    'shadowChromaGateL',
    'chromaGateThreshold',  // Note: NOT chromaGate (that's a ParameterGenerator multiplier)
    'peakFinderMaxPeaks',
    'peakFinderBlacklistedSectors',
    'peakFinderPreferredSectors',
    'neutralSovereigntyThreshold',
    'colorMode',            // Used via grayscaleOnly derivation
    'ignoreTransparent',

    // Median cut split strategy
    'splitMode',

    // Distance metric (for palette operations inside posterization)
    'distanceMetric',
]);

/** Keys read by SeparationEngine.mapPixelsToPaletteAsync() */
const SEPARATION_ENGINE_READS = new Set([
    'ditherType',
    'meshCount',            // Canonical name
    'mesh',                 // Legacy alias (reveal-adobe)
    'dpi',
    'distanceMetric',       // Via normalizeDistanceConfig()
]);

/** Keys read by ProxyEngine from its config arguments */
const PROXY_ENGINE_READS = new Set([
    'engine',               // Routing: distilled vs standard posterize
    'preprocessingIntensity',
    'targetColors',
    'targetColorsSlider',   // Legacy alias
    'ditherType',
    'distanceMetric',
    'bitDepth',
    'substrateMode',
]);

// ─── Known Unimplemented Parameters ──────────────────────────────────
// These are generated by ParameterGenerator and stored in config/state,
// but NO engine currently reads them. They have UI controls that do nothing.
// When you implement one, move it to the appropriate ENGINE_READS set above.
const KNOWN_UNIMPLEMENTED = new Set([
    'vibrancyThreshold',            // UI slider, no engine reads it
    'detailRescue',                 // UI slider, no engine reads it
    'medianPass',                   // UI checkbox, no engine reads it
    'maskProfile',                  // UI dropdown, ProductionWorker doesn't use it yet
    'neutralCentroidClampThreshold', // UI slider, no engine reads it
    // meshSize — now correctly mapped to meshCount in toEngineOptions()
]);

// ─── Metadata / Non-Engine Keys ──────────────────────────────────────
// These are in the ParameterGenerator output but are not engine options.
// They carry context information (archetype name, image stats, etc).
const METADATA_KEYS = new Set([
    'id',
    'name',
    'meta',
    'rangeClamp',
    'preprocessing',        // Preprocessing intensity descriptor (separate from engine option)
]);

// ─── Derived / Multiplier Keys ───────────────────────────────────────
// These affect other params during generate() but aren't passed to engines directly.
const DERIVED_KEYS = new Set([
    'chromaGate',           // Multiplier applied to cWeight at generate time
    'saturationBoost',      // Legacy alias for vibrancyBoost
    // meshSize — session-level, not in generate() output. Mapped to meshCount in toEngineOptions().
]);

// ─── Keys Consumed Outside Core Engines ──────────────────────────────
// These are consumed by ProductionWorker, PhotoshopBridge, or SessionState
// but not by PosterizationEngine/SeparationEngine directly.
const NON_ENGINE_CONSUMED = new Set([
    'shadowClamp',          // MechanicalKnobs.applyShadowClamp (positional arg)
    'speckleRescue',        // MechanicalKnobs.applySpeckleRescue (positional arg)
    'minVolume',            // MechanicalKnobs.applyMinVolume (positional arg)
    'preprocessingIntensity', // Applied by ProxyEngine/ProductionWorker before posterize
    'substrateTolerance',   // Consumed by PosterizationEngine (already in POSTERIZATION_ENGINE_READS)
]);

// ─── Helper: Generate a realistic config from DNA ────────────────────
function generateTestConfig() {
    // Minimal DNA that passes ParameterGenerator validation
    const dna = {
        l: 55, c: 40, k: 15, lStd: 18,
        entropy: 0.7, colorTemp: 0.5,
        maxL: 95, minL: 5, maxC: 65,
        sectorWeights: [0.1, 0.1, 0.1, 0.05, 0.05, 0.05, 0.1, 0.1, 0.1, 0.05, 0.1, 0.1],
        sectorChromas: [30, 25, 20, 15, 10, 15, 20, 25, 30, 25, 20, 15],
    };
    return ParameterGenerator.generate(dna, { bitDepth: 16 });
}

// ═══════════════════════════════════════════════════════════════════════
// Tests
// ═══════════════════════════════════════════════════════════════════════

describe('Parameter Flow Contracts', () => {

    // ─── 1. Every generate() output key is accounted for ─────────────
    describe('ParameterGenerator.generate() completeness', () => {
        it('every config key is mapped to an engine, unimplemented, metadata, or derived', () => {
            const config = generateTestConfig();

            // All known destinations
            const allAccountedFor = new Set([
                ...POSTERIZATION_ENGINE_READS,
                ...SEPARATION_ENGINE_READS,
                ...PROXY_ENGINE_READS,
                ...KNOWN_UNIMPLEMENTED,
                ...METADATA_KEYS,
                ...DERIVED_KEYS,
                ...NON_ENGINE_CONSUMED,
            ]);

            const unmapped = [];
            for (const key of Object.keys(config)) {
                if (!allAccountedFor.has(key)) {
                    unmapped.push(key);
                }
            }

            expect(unmapped).toEqual([]);
        });
    });

    // ─── 2. toEngineOptions() produces all engine-required keys ──────
    describe('ParameterGenerator.toEngineOptions() coverage', () => {
        let config, opts;

        beforeAll(() => {
            config = generateTestConfig();
            opts = ParameterGenerator.toEngineOptions(config, { bitDepth: 16 });
        });

        it('emits both targetColors and targetColorsSlider', () => {
            expect(opts.targetColors).toBeDefined();
            expect(opts.targetColorsSlider).toBeDefined();
            expect(opts.targetColors).toBe(opts.targetColorsSlider);
        });

        it('maps meshSize to meshCount (not meshSize)', () => {
            const configWithMesh = { ...config, meshSize: 230 };
            const optsWithMesh = ParameterGenerator.toEngineOptions(configWithMesh);
            expect(optsWithMesh.meshCount).toBe(230);
            expect(optsWithMesh.meshSize).toBeUndefined();
        });

        it('omits meshCount when meshSize is undefined', () => {
            const configNoMesh = { ...config };
            delete configNoMesh.meshSize;
            const optsNoMesh = ParameterGenerator.toEngineOptions(configNoMesh);
            expect(optsNoMesh.meshCount).toBeUndefined();
        });

        it('includes all PosterizationEngine keys that are in the config', () => {
            // These keys should pass through from config → toEngineOptions
            const posterizeKeys = [
                'engine', 'centroidStrategy', 'distanceMetric',
                'lWeight', 'cWeight', 'bWeight', 'blackBias',
                'vibrancyMode', 'vibrancyBoost',
                'highlightThreshold', 'highlightBoost',
                'paletteReduction', 'enablePaletteReduction',
                'substrateMode', 'substrateTolerance',
                'enableHueGapAnalysis', 'hueLockAngle',
                'shadowPoint', 'preserveWhite', 'preserveBlack',
                'neutralSovereigntyThreshold',
                'chromaAxisWeight', 'neutralIsolationThreshold', 'warmABoost',
                'peakFinderMaxPeaks', 'peakFinderBlacklistedSectors',
                'refinementPasses', 'shadowChromaGateL',
                'ignoreTransparent', 'colorMode', 'splitMode',
            ];

            for (const key of posterizeKeys) {
                expect(opts[key]).toBeDefined();
            }
        });

        it('includes all SeparationEngine keys', () => {
            expect(opts.ditherType).toBeDefined();
            expect(opts.distanceMetric).toBeDefined();
        });
    });

    // ─── 3. SeparationEngine accepts meshCount ───────────────────────
    describe('SeparationEngine meshCount flow', () => {
        it('reads meshCount from options and computes scale', async () => {
            // Create minimal 3-pixel image and 2-color palette
            const labPixels = new Uint16Array([
                16384, 16384, 16384,  // neutral gray
                32000, 16384, 16384,  // bright gray
                8000,  16384, 16384,  // dark gray
            ]);
            const palette = [
                { L: 50, a: 0, b: 0 },
                { L: 90, a: 0, b: 0 },
            ];

            // This should not throw — meshCount is read correctly
            const indices = await SeparationEngine.mapPixelsToPaletteAsync(
                labPixels, palette, null, 3, 1,
                { ditherType: 'blue-noise', meshCount: 230, dpi: 300 }
            );
            expect(indices).toBeInstanceOf(Uint8Array);
            expect(indices.length).toBe(3);
        });

        it('accepts legacy "mesh" name', async () => {
            const labPixels = new Uint16Array([16384, 16384, 16384]);
            const palette = [{ L: 50, a: 0, b: 0 }];

            const indices = await SeparationEngine.mapPixelsToPaletteAsync(
                labPixels, palette, null, 1, 1,
                { ditherType: 'blue-noise', mesh: 230 }
            );
            expect(indices).toBeInstanceOf(Uint8Array);
        });
    });

    // ─── 4. chromaGate affects cWeight via _applyChromaGate ─────────
    describe('chromaGate × cWeight multiplication', () => {
        it('chromaGate multiplies cWeight for high-chroma images (maxC > 60)', () => {
            const params = { cWeight: 2.0, chromaGate: 1.5 };
            const dna = { maxC: 80 };  // Above threshold (60)
            ParameterGenerator._applyChromaGate(params, dna);
            expect(params.cWeight).toBe(3.0);  // 2.0 × 1.5
        });

        it('chromaGate has no effect for low-chroma images (maxC <= 60)', () => {
            const params = { cWeight: 2.0, chromaGate: 1.5 };
            const dna = { maxC: 40 };  // Below threshold
            ParameterGenerator._applyChromaGate(params, dna);
            expect(params.cWeight).toBe(2.0);  // Unchanged
        });

        it('chromaGate=0 is a no-op', () => {
            const params = { cWeight: 2.0, chromaGate: 0 };
            const dna = { maxC: 80 };
            ParameterGenerator._applyChromaGate(params, dna);
            expect(params.cWeight).toBe(2.0);  // Unchanged (falsy gate)
        });

        it('missing chromaGate is a no-op', () => {
            const params = { cWeight: 2.0 };
            const dna = { maxC: 80 };
            ParameterGenerator._applyChromaGate(params, dna);
            expect(params.cWeight).toBe(2.0);
        });
    });

    // ─── 5. No param is in multiple conflicting categories ───────────
    describe('category exclusivity', () => {
        // These are the SessionState category sets (mirrored here for testing)
        const MECHANICAL = new Set(['minVolume', 'speckleRescue', 'shadowClamp']);
        const PRODUCTION = new Set(['trapSize', 'meshSize']);
        const STRUCTURAL = new Set([
            'targetColors', 'engine', 'centroidStrategy', 'distanceMetric',
            'lWeight', 'cWeight', 'blackBias',
            'vibrancyMode', 'vibrancyBoost',
            'highlightThreshold', 'highlightBoost',
            'paletteReduction', 'enablePaletteReduction',
            'substrateMode', 'substrateTolerance',
            'enableHueGapAnalysis', 'hueLockAngle',
            'shadowPoint', 'colorMode',
            'preserveWhite', 'preserveBlack',
            'neutralCentroidClampThreshold', 'neutralSovereigntyThreshold',
            'chromaGate',
            'ditherType',
            'preprocessingIntensity', 'ignoreTransparent',
            'refinementPasses', 'splitMode',
        ]);

        it('no param is in both STRUCTURAL and PRODUCTION', () => {
            const overlap = [...STRUCTURAL].filter(k => PRODUCTION.has(k));
            expect(overlap).toEqual([]);
        });

        it('no param is in both STRUCTURAL and MECHANICAL', () => {
            const overlap = [...STRUCTURAL].filter(k => MECHANICAL.has(k));
            expect(overlap).toEqual([]);
        });

        it('no param is in both PRODUCTION and MECHANICAL', () => {
            const overlap = [...PRODUCTION].filter(k => MECHANICAL.has(k));
            expect(overlap).toEqual([]);
        });
    });

    // ─── 6. Known unimplemented params are truly unimplemented ───────
    describe('unimplemented params documentation', () => {
        it('KNOWN_UNIMPLEMENTED params are not in any engine contract', () => {
            for (const key of KNOWN_UNIMPLEMENTED) {
                expect(POSTERIZATION_ENGINE_READS.has(key)).toBe(false);
                expect(SEPARATION_ENGINE_READS.has(key)).toBe(false);
                // If you just implemented one and this fails: move it from
                // KNOWN_UNIMPLEMENTED to the appropriate ENGINE_READS set!
            }
        });
    });

    // ─── 7. ProxyEngine config keys match what ParameterGenerator provides
    describe('ProxyEngine config compatibility', () => {
        it('generate() output has all keys ProxyEngine reads', () => {
            const config = generateTestConfig();
            for (const key of PROXY_ENGINE_READS) {
                // targetColorsSlider is a legacy alias — config has targetColors
                if (key === 'targetColorsSlider') continue;
                // bitDepth comes from the caller, not generate()
                if (key === 'bitDepth') continue;
                expect(config[key]).toBeDefined();
            }
        });
    });

    // ─── 8. Round-trip: generate → toEngineOptions preserves values ──
    describe('generate → toEngineOptions value preservation', () => {
        it('numeric values survive the round-trip unchanged', () => {
            const config = generateTestConfig();
            const opts = ParameterGenerator.toEngineOptions(config);

            const numericKeys = [
                'lWeight', 'cWeight', 'bWeight', 'blackBias',
                'vibrancyBoost', 'highlightThreshold', 'highlightBoost',
                'paletteReduction', 'substrateTolerance', 'hueLockAngle',
                'shadowPoint', 'refinementPasses',
            ];

            for (const key of numericKeys) {
                expect(opts[key]).toBe(config[key]);
            }
        });

        it('string values survive the round-trip unchanged', () => {
            const config = generateTestConfig();
            const opts = ParameterGenerator.toEngineOptions(config);

            const stringKeys = [
                'engine', 'centroidStrategy', 'distanceMetric',
                'ditherType', 'vibrancyMode', 'substrateMode', 'colorMode',
            ];

            for (const key of stringKeys) {
                expect(opts[key]).toBe(config[key]);
            }
        });

        it('boolean values survive the round-trip unchanged', () => {
            const config = generateTestConfig();
            const opts = ParameterGenerator.toEngineOptions(config);

            const boolKeys = [
                'enablePaletteReduction', 'enableHueGapAnalysis',
                'preserveWhite', 'preserveBlack', 'ignoreTransparent',
            ];

            for (const key of boolKeys) {
                expect(opts[key]).toBe(config[key]);
            }
        });
    });
});
