/**
 * ingest.test.js — Unit tests for TIFF/PSD pixel conversion.
 *
 * Tests the four TIFF conversion functions against ground truth from the
 * horse PSD fixture. Each format variant (Lab/RGB × 8/16-bit) must produce
 * engine Lab values that match the PSD reference within tolerance.
 *
 * Tolerances:
 *   Lab TIFF → PSD:  ≤2 engine units (quantization in Lab↔TIFF round-trip)
 *   RGB TIFF → PSD:  ≤200 engine units (Lab→RGB→Lab has gamut/precision loss)
 *
 * Fixtures generated by test/fixtures/create-horse-fixtures.js from the
 * Photoshop 16-bit Lab horse PSD (0B9A4230).
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const fs = require('fs');
const path = require('path');
const UTIF = require('utif2');
const { LabEncoding } = require('@electrosaur-labs/core');
const { readPsd } = require('@electrosaur-labs/psd-reader');
const {
    convertCieLab16, convertCieLab8, convertRgb16, convertRgb8,
} = require('../../src/ingest');

const FIXTURES = path.join(__dirname, '..', 'fixtures');

function loadTiff(filename) {
    const buf = fs.readFileSync(path.join(FIXTURES, filename));
    const ifds = UTIF.decode(buf);
    UTIF.decodeImage(buf, ifds[0]);
    const ifd = ifds[0];
    return {
        data: ifd.data,
        width: ifd.width || ifd.t256?.[0],
        height: ifd.height || ifd.t257?.[0],
        photometric: ifd.t262?.[0],
        bitsPerSample: ifd.t258?.[0],
        samplesPerPixel: ifd.t277?.[0] || 3,
    };
}

function loadReference() {
    const ref = JSON.parse(fs.readFileSync(path.join(FIXTURES, 'horse-reference.json')));
    return {
        engineLab: new Uint16Array(ref.allPixels),
        width: ref.width,
        height: ref.height,
    };
}

function loadPsdFixture() {
    const buf = fs.readFileSync(path.join(FIXTURES, 'horse-lab16.psd'));
    const psd = readPsd(buf);
    const pixelCount = psd.width * psd.height;
    const engineLab = LabEncoding.convertPsd16bitToEngineLab(psd.data, pixelCount);
    return { engineLab, width: psd.width, height: psd.height };
}

/**
 * Compare two engine Lab buffers. Returns { maxDiff, meanDiff, worstPixel }.
 */
function compareBuffers(actual, expected, pixelCount) {
    let maxDiff = 0;
    let totalDiff = 0;
    let worstPixel = -1;
    for (let i = 0; i < pixelCount; i++) {
        const dL = Math.abs(actual[i * 3] - expected[i * 3]);
        const da = Math.abs(actual[i * 3 + 1] - expected[i * 3 + 1]);
        const db = Math.abs(actual[i * 3 + 2] - expected[i * 3 + 2]);
        const pixelMax = Math.max(dL, da, db);
        if (pixelMax > maxDiff) {
            maxDiff = pixelMax;
            worstPixel = i;
        }
        totalDiff += dL + da + db;
    }
    return {
        maxDiff,
        meanDiff: totalDiff / (pixelCount * 3),
        worstPixel,
    };
}

describe('ingest: TIFF conversion functions', () => {
    let ref;

    beforeAll(() => {
        ref = loadReference();
    });

    describe('PSD fixture (sanity check)', () => {
        it('PSD fixture matches reference exactly', () => {
            const psd = loadPsdFixture();
            expect(psd.width).toBe(ref.width);
            expect(psd.height).toBe(ref.height);
            const stats = compareBuffers(psd.engineLab, ref.engineLab, ref.width * ref.height);
            expect(stats.maxDiff).toBe(0);
        });
    });

    describe('16-bit CIELab TIFF', () => {
        it('decodes with correct dimensions and metadata', () => {
            const tiff = loadTiff('horse-lab16.tif');
            expect(tiff.width).toBe(64);
            expect(tiff.height).toBe(64);
            expect(tiff.photometric).toBe(8);
            expect(tiff.bitsPerSample).toBe(16);
        });

        it('converts to engine Lab matching PSD reference (tolerance ≤2)', () => {
            const tiff = loadTiff('horse-lab16.tif');
            const pixelCount = tiff.width * tiff.height;
            const lab16bit = new Uint16Array(pixelCount * 3);
            convertCieLab16(tiff.data, lab16bit, pixelCount, tiff.samplesPerPixel);

            const stats = compareBuffers(lab16bit, ref.engineLab, pixelCount);
            expect(stats.maxDiff).toBeLessThanOrEqual(2);
            expect(stats.meanDiff).toBeLessThan(1);
        });

        it('neutral a/b maps to engine 16384', () => {
            // Construct a synthetic neutral pixel: L=50%, a=0, b=0
            const rawBytes = new Uint8Array(6);
            const dv = new DataView(rawBytes.buffer);
            dv.setUint16(0, 32768, true);  // L: mid-range unsigned
            dv.setInt16(2, 0, true);       // a: 0 = neutral
            dv.setInt16(4, 0, true);       // b: 0 = neutral
            const lab16bit = new Uint16Array(3);
            convertCieLab16(rawBytes, lab16bit, 1, 3);
            expect(lab16bit[1]).toBe(16384); // a neutral
            expect(lab16bit[2]).toBe(16384); // b neutral
        });

        it('negative a/b values produce engine values below 16384', () => {
            // a = -128 in TIFF: Int16 = -128 * 256 = -32768
            const rawBytes = new Uint8Array(6);
            const dv = new DataView(rawBytes.buffer);
            dv.setUint16(0, 32768, true);
            dv.setInt16(2, -32768, true);   // a: most negative
            dv.setInt16(4, -32768, true);   // b: most negative
            const lab16bit = new Uint16Array(3);
            convertCieLab16(rawBytes, lab16bit, 1, 3);
            expect(lab16bit[1]).toBeLessThan(16384);
            expect(lab16bit[2]).toBeLessThan(16384);
        });
    });

    describe('8-bit CIELab TIFF', () => {
        it('decodes with correct dimensions and metadata', () => {
            const tiff = loadTiff('horse-lab8.tif');
            expect(tiff.width).toBe(64);
            expect(tiff.height).toBe(64);
            expect(tiff.photometric).toBe(8);
            expect(tiff.bitsPerSample).toBe(8);
        });

        it('converts to engine Lab matching PSD reference (8-bit quantization tolerance)', () => {
            // 8-bit Lab: L quantized to 256 levels (vs 32768), a/b clamped to -128..+127
            // Worst case: b*=128 clamped to 127 → ~128 engine units error
            // Plus general 8-bit quantization: each channel ±64 engine units
            const tiff = loadTiff('horse-lab8.tif');
            const pixelCount = tiff.width * tiff.height;
            const lab16bit = new Uint16Array(pixelCount * 3);
            convertCieLab8(tiff.data, lab16bit, pixelCount, tiff.samplesPerPixel);

            const stats = compareBuffers(lab16bit, ref.engineLab, pixelCount);
            expect(stats.maxDiff).toBeLessThanOrEqual(256);
            expect(stats.meanDiff).toBeLessThan(50);
        });

        it('neutral a/b byte (0) maps to engine 16384', () => {
            // 8-bit CIELab: a/b are signed bytes where 0 = neutral
            const rawBytes = new Uint8Array([128, 0, 0]); // L=mid, a=neutral, b=neutral
            const lab16bit = new Uint16Array(3);
            convertCieLab8(rawBytes, lab16bit, 1, 3);
            expect(lab16bit[1]).toBe(16384);
            expect(lab16bit[2]).toBe(16384);
        });
    });

    describe('16-bit RGB TIFF', () => {
        it('decodes with correct dimensions and metadata', () => {
            const tiff = loadTiff('horse-rgb16.tif');
            expect(tiff.width).toBe(64);
            expect(tiff.height).toBe(64);
            expect(tiff.photometric).toBe(2);
            expect(tiff.bitsPerSample).toBe(16);
        });

        it('round-trips RGB values correctly (converter matches direct rgbToLab)', () => {
            // RGB TIFF can't match PSD Lab due to gamut clipping on saturated colors.
            // Instead, verify our converter produces the same Lab as directly calling
            // rgbToLab on the same RGB values — this tests the converter, not the gamut.
            const tiff = loadTiff('horse-rgb16.tif');
            const pixelCount = tiff.width * tiff.height;
            const u16 = new Uint16Array(tiff.data.buffer, tiff.data.byteOffset, tiff.data.byteLength / 2);

            // What our converter produces
            const actual = new Uint16Array(pixelCount * 3);
            convertRgb16(tiff.data, actual, pixelCount, tiff.samplesPerPixel);

            // What rgbToLab should produce from the same RGB values
            const expected = new Uint16Array(pixelCount * 3);
            for (let i = 0; i < pixelCount; i++) {
                const si = i * tiff.samplesPerPixel;
                const r = Math.round(u16[si]     * (255 / 65535));
                const g = Math.round(u16[si + 1] * (255 / 65535));
                const b = Math.round(u16[si + 2] * (255 / 65535));
                const lab = LabEncoding.rgbToLab({ r, g, b });
                expected[i * 3]     = Math.round((lab.L / 100) * 32768);
                expected[i * 3 + 1] = Math.round(((lab.a + 128) / 256) * 32768);
                expected[i * 3 + 2] = Math.round(((lab.b + 128) / 256) * 32768);
            }

            const stats = compareBuffers(actual, expected, pixelCount);
            expect(stats.maxDiff).toBe(0); // exact match — same code path
        });

        it('pure white RGB maps to high L, neutral a/b', () => {
            const rawBytes = new Uint8Array(6);
            const dv = new DataView(rawBytes.buffer);
            dv.setUint16(0, 65535, true); // R
            dv.setUint16(2, 65535, true); // G
            dv.setUint16(4, 65535, true); // B
            const lab16bit = new Uint16Array(3);
            convertRgb16(rawBytes, lab16bit, 1, 3);
            expect(lab16bit[0]).toBeGreaterThan(32000); // L near max
            // a/b should be near neutral (16384) for white
            expect(Math.abs(lab16bit[1] - 16384)).toBeLessThan(500);
            expect(Math.abs(lab16bit[2] - 16384)).toBeLessThan(500);
        });
    });

    describe('8-bit RGB TIFF', () => {
        it('decodes with correct dimensions and metadata', () => {
            const tiff = loadTiff('horse-rgb8.tif');
            expect(tiff.width).toBe(64);
            expect(tiff.height).toBe(64);
            expect(tiff.photometric).toBe(2);
            expect(tiff.bitsPerSample).toBe(8);
        });

        it('round-trips RGB values correctly (converter matches direct rgbToLab)', () => {
            const tiff = loadTiff('horse-rgb8.tif');
            const pixelCount = tiff.width * tiff.height;

            const actual = new Uint16Array(pixelCount * 3);
            convertRgb8(tiff.data, actual, pixelCount, tiff.samplesPerPixel);

            const expected = new Uint16Array(pixelCount * 3);
            for (let i = 0; i < pixelCount; i++) {
                const si = i * tiff.samplesPerPixel;
                const lab = LabEncoding.rgbToLab({ r: tiff.data[si], g: tiff.data[si + 1], b: tiff.data[si + 2] });
                expected[i * 3]     = Math.round((lab.L / 100) * 32768);
                expected[i * 3 + 1] = Math.round(((lab.a + 128) / 256) * 32768);
                expected[i * 3 + 2] = Math.round(((lab.b + 128) / 256) * 32768);
            }

            const stats = compareBuffers(actual, expected, pixelCount);
            expect(stats.maxDiff).toBe(0);
        });

        it('pure black RGB maps to low L', () => {
            const rawBytes = new Uint8Array([0, 0, 0]);
            const lab16bit = new Uint16Array(3);
            convertRgb8(rawBytes, lab16bit, 1, 3);
            expect(lab16bit[0]).toBeLessThan(100); // L near 0
        });

        it('pure red RGB maps to positive a', () => {
            const rawBytes = new Uint8Array([255, 0, 0]);
            const lab16bit = new Uint16Array(3);
            convertRgb8(rawBytes, lab16bit, 1, 3);
            expect(lab16bit[1]).toBeGreaterThan(16384); // a > neutral (red is +a)
        });
    });

    describe('cross-format consistency', () => {
        it('Lab16 TIFF and PSD produce identical engine Lab', () => {
            const tiff = loadTiff('horse-lab16.tif');
            const psd = loadPsdFixture();
            const pixelCount = tiff.width * tiff.height;
            const tiffLab = new Uint16Array(pixelCount * 3);
            convertCieLab16(tiff.data, tiffLab, pixelCount, tiff.samplesPerPixel);

            const stats = compareBuffers(tiffLab, psd.engineLab, pixelCount);
            expect(stats.maxDiff).toBeLessThanOrEqual(2);
        });

        it('RGB8 and RGB16 TIFFs produce similar engine Lab', () => {
            const tiff8 = loadTiff('horse-rgb8.tif');
            const tiff16 = loadTiff('horse-rgb16.tif');
            const pixelCount = tiff8.width * tiff8.height;

            const lab8 = new Uint16Array(pixelCount * 3);
            const lab16 = new Uint16Array(pixelCount * 3);
            convertRgb8(tiff8.data, lab8, pixelCount, tiff8.samplesPerPixel);
            convertRgb16(tiff16.data, lab16, pixelCount, tiff16.samplesPerPixel);

            const stats = compareBuffers(lab8, lab16, pixelCount);
            // Both came from the same Lab source → should be very close
            expect(stats.maxDiff).toBeLessThanOrEqual(5);
        });

        it('all four TIFF variants produce L values in similar range', () => {
            const variants = [
                { file: 'horse-lab16.tif', fn: convertCieLab16 },
                { file: 'horse-lab8.tif', fn: convertCieLab8 },
                { file: 'horse-rgb16.tif', fn: convertRgb16 },
                { file: 'horse-rgb8.tif', fn: convertRgb8 },
            ];
            const lRanges = [];
            for (const { file, fn } of variants) {
                const tiff = loadTiff(file);
                const pixelCount = tiff.width * tiff.height;
                const lab = new Uint16Array(pixelCount * 3);
                fn(tiff.data, lab, pixelCount, tiff.samplesPerPixel);
                let minL = 65535, maxL = 0;
                for (let i = 0; i < pixelCount; i++) {
                    minL = Math.min(minL, lab[i * 3]);
                    maxL = Math.max(maxL, lab[i * 3]);
                }
                lRanges.push({ file, minL, maxL });
            }
            // All should have similar L range (horse face has darks and lights)
            for (const r of lRanges) {
                expect(r.maxL - r.minL).toBeGreaterThan(5000); // meaningful dynamic range
            }
        });
    });
});
