export const PRESETS = {
    "vibrant_tonal": {
        "id": "vibrant_tonal",
        "name": "Vibrant Tonal / High-Chroma Protect",
        "description": "Photographic images with extreme chroma spikes (e.g. neon yellows in a dark scene)",
        "engineType": "reveal",
        "centroidStrategy": "SALIENCY",
        "lWeight": 0.2,
        "cWeight": 6,
        "blackBias": 3.5,
        "substrateMode": "auto",
        "substrateTolerance": 2.5,
        "vibrancyMode": "exponential",
        "vibrancyBoost": 1.8,
        "vibrancyThreshold": 5,
        "highlightThreshold": 95,
        "highlightBoost": 1.4,
        "enablePaletteReduction": true,
        "paletteReduction": 3,
        "hueLockAngle": 45,
        "shadowPoint": 10,
        "colorMode": "color",
        "targetColorsSlider": 10,
        "preserveWhite": false,
        "preserveBlack": false,
        "ignoreTransparent": true,
        "enableHueGapAnalysis": true,
        "ditherType": "BlueNoise",
        "maskProfile": "Gray Gamma 2.2"
    },
    "warm_tonal_optimized": {
        "id": "warm_tonal_optimized",
        "name": "Warm Tonal / Yellow Protect",
        "description": "Optimized for photographic images where yellows must remain sovereign from browns and earthy tones.",
        "engineType": "reveal",
        "centroidStrategy": "SALIENCY",
        "lWeight": 0.3,
        "cWeight": 5,
        "blackBias": 4,
        "substrateMode": "auto",
        "substrateTolerance": 3,
        "vibrancyMode": "exponential",
        "vibrancyBoost": 1.8,
        "vibrancyThreshold": 8,
        "highlightThreshold": 96,
        "highlightBoost": 1.6,
        "enablePaletteReduction": true,
        "paletteReduction": 4,
        "hueLockAngle": 45,
        "shadowPoint": 12,
        "colorMode": "color",
        "targetColorsSlider": 10,
        "preserveWhite": true,
        "preserveBlack": false,
        "ignoreTransparent": true,
        "enableHueGapAnalysis": true,
        "ditherType": "BlueNoise",
        "maskProfile": "Gray Gamma 2.2"
    },
    "bright_desaturated": {
        "id": "bright_desaturated",
        "name": "Bright Desaturated / High-Key Contrast",
        "description": "Bright, washed-out photographic images with extreme contrast and minimal color (overexposed look, bleached aesthetics)",
        "engineType": "reveal",
        "centroidStrategy": "SALIENCY",
        "lWeight": 1.2,
        "cWeight": 0.8,
        "blackBias": 3,
        "substrateMode": "white",
        "substrateTolerance": 4,
        "vibrancyMode": "subtle",
        "vibrancyBoost": 0.9,
        "vibrancyThreshold": 20,
        "highlightThreshold": 92,
        "highlightBoost": 1.8,
        "enablePaletteReduction": true,
        "paletteReduction": 7,
        "hueLockAngle": 20,
        "shadowPoint": 8,
        "colorMode": "color",
        "targetColorsSlider": 7,
        "preserveWhite": true,
        "preserveBlack": true,
        "ignoreTransparent": true,
        "enableHueGapAnalysis": true,
        "ditherType": "none",
        "maskProfile": "Gray Gamma 2.2"
    },
    "noir_shadow": {
        "id": "noir_shadow",
        "name": "Deep Shadow / Noir",
        "description": "Dark, low color, high contrast (film noir, woodcuts, ink drawings)",
        "engineType": "reveal",
        "centroidStrategy": "SALIENCY",
        "lWeight": 1.5,
        "cWeight": 1.2,
        "blackBias": 8,
        "substrateMode": "black",
        "substrateTolerance": 1.5,
        "vibrancyMode": "exponential",
        "vibrancyBoost": 1.4,
        "vibrancyThreshold": 10,
        "highlightThreshold": 80,
        "highlightBoost": 3,
        "enablePaletteReduction": true,
        "paletteReduction": 7.5,
        "hueLockAngle": 12,
        "shadowPoint": 2,
        "colorMode": "color",
        "targetColorsSlider": 6,
        "preserveWhite": false,
        "preserveBlack": true,
        "ignoreTransparent": true,
        "enableHueGapAnalysis": true,
        "ditherType": "none",
        "maskProfile": "Gray Gamma 2.2"
    },
    "bright_desaturated_2": {
        "id": "bright_desaturated_2",
        "name": "Bright Desaturated / High-Key Contrast",
        "description": "Bright, washed-out photographic images with extreme contrast and minimal color (overexposed look, bleached aesthetics)",
        "engineType": "reveal",
        "centroidStrategy": "SALIENCY",
        "lWeight": 1.2,
        "cWeight": 0.8,
        "blackBias": 3,
        "substrateMode": "white",
        "substrateTolerance": 4,
        "vibrancyMode": "subtle",
        "vibrancyBoost": 0.9,
        "vibrancyThreshold": 20,
        "highlightThreshold": 92,
        "highlightBoost": 1.8,
        "enablePaletteReduction": true,
        "paletteReduction": 7,
        "hueLockAngle": 20,
        "shadowPoint": 8,
        "colorMode": "color",
        "targetColorsSlider": 7,
        "preserveWhite": true,
        "preserveBlack": true,
        "ignoreTransparent": true,
        "enableHueGapAnalysis": true,
        "ditherType": "none",
        "maskProfile": "Gray Gamma 2.2"
    }
};